title:            Chaos
description:      My constant struggle to manage chaos.
url:              http://rustyautopsy.github.io
signoff:          Travis Dolan
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Skills
    url:          /skills
  - name:         Email
    url:          mailto:travis.dolan@gmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/rustyautopsy/
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
