title:            Managing Chaos
description:      My constant struggle to manage chaos.
url:              http://rustyautopsy.github.io
signoff:          Travis Dolan
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   602553569857235
google_analytics: UA-53212816-1

links:
  - name:         About
    url:          /about
  - name:         Skills
    url:          /skills
  - name:         Rabbit Holes
    url:          /rabbitholes
  - name:         Email
    url:          mailto:travis.dolan@gmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/rustyautopsy/
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
